# -*- coding: utf-8 -*-
"""Creating 1D array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1Vk9zNIynJ4eKuZwgMmuFbqbV6bfiOu

## **function to creating 1D Array**

**1. Arrange :**
- array-valued version on built-in python range
- **syn :**  np.arrange(start,end,step)
"""

import numpy as np

a = np.arange(10)
print(a)

a = np.arange(0,20,2)
print(a)

"""**2.linspace**

- retruns evenly spaced numbers over a specified interval
- **Syn :** np.linspace(start,end,num_of_samples)
"""

a= np.linspace(1,100,5)
print(a)

"""**3.random.randint**
- Retrun random integers from start(include) to end(exclude)
- **Syn :** np.randomint(start, end , num_of_sample)
"""

a= np.random.randint(1,10,3)
a

"""**zeroes**
- create array with zeroes
- **syn:** np.zeros(shape)
"""

np.zeros(5)               #by default it takes datatype as float

"""**ones**
- one matrix or unity matrix
- create array with ones
- **syn:** np.ones(shape)
"""

np.ones(5)

"""## Accessing the elements/ Extarcting the values"""

a = np.array([10,20,30,40,50,60])
print(a)

a[0]                            #Acessing single value through indexing

a[::-1]                          #Acessing multiple value through slicing

"""**Acessing multiple value through indexing**
- **Synt :** variable_name[index number] --->for single value
- varible_name[[list of index numbers    ---> for multiple value
"""

a = np.array([10,20,30,40,50,60])
print(a)

b= a[[1,2,5]]                                    #Acessing multiple value through indexing
print(b)

"""### modify the values"""

#add a sigle value in array
a = [1,2,3,4]
b = np.array(a)
print(b)

c = np.append(b,45)
print(c)

a = [1,2,3,4]
b = np.array(a)
print(b)

c = np.append(b,[45,56,67])               #adding multiple values
print(c)

f = np.array([23,54,18,65])
g=np.delete(f,2)                              #removing multiple  items
print(g)

#removing single valu
l=[1,9,4,6]
l.pop(1)
print(l)

l=np.array([1,9,41,62,45,76])

l[[1,2,3]] = 90                     #Replacing a multiple index numbers with single value
print(l)

l = np.array([23,45,67,89])
l[[1,2]] = [54,76]                 #Replacing a multiple inex numbers with multiple values
print(l)

"""**Copy array**"""

#shallow copy
a = np.array([23,45,32,54])
print("a:",a)
b= a.copy()
print("b:",b)
b[0]=100
print("after modifying b:",b)
print("After modfiying a remians same: ",a)

"""**Sorting array**"""

a= np.array([34,1,100,67,80])
print(a)

b= np.sort(a)
print(b)

