# -*- coding: utf-8 -*-
"""Loading Excel or CSV Data .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170vKrBRBXCvI5VPOubeIO2-9VAlWr-yh
"""

import numpy as np

import pandas as pd

"""## Load the data"""

pd.read_excel("C:\\Users\\DELL\\Desktop\\Example.xlsx")

"""**Method 1**"""

pd.read_excel("C:\\Users\\DELL\\Downloads\\PandasExample.xlsx")

"""**Method 2**"""

pd.read_excel("C:/Users/DELL/Downloads/PandasExample.xlsx")

"""**Method 3**"""

pd.read_excel(r"C:\Users\DELL\Downloads\PandasExample.xlsx")

pwd    #present working directory

"""**Method 4**"""

pd.read_excel("PandasExample.xlsx")   #works only whne excel file and jupyter notebook in a same folder or location

"""### **Loading CSV file**"""

pd.read_csv(r"C:\Users\DELL\Downloads\Pandas Example CSV.csv")

df =pd.read_excel(r"C:\Users\DELL\Downloads\PandasExample.xlsx")
df

df.iloc[1,:]             #in iloc 1 ois considered as index row name

df.loc[ : ,"Salary"]     #in loc we need to put a names only whether it may be a row or column not a number

