# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GxjaJhSHse6uSRwvD3P_tP6gSQI1GJm5

# NumPy
"""

import numpy as np

l =[1,2,3,4]
s= np.array(l)
s+10

l1=[10,20,30,40]
l2=[40]

np.array(l1)+ np.array(l2)

l1=[10,20,30,40]
l2=[40,30,40,30]

np.array(l1)+ np.array(l2)

np.array(l)            #list converted to array

x = (12,34,56,78)

array_x= np.array(x)

print(array_x)

array_x.ndim

#list to array
list = [12,56,True,"True"]

array_list = np.array(list)
print(array_list)









